vile:
  ignore: [
      "node_modules",
      ".build",
      ".test",
      ".git",
      "coverage",
      "tmp",
      "lib"
    ]

coverage:
  config:
    path: coverage/lcov.info

length:
  config:
    file: 120
    line: 80
